version: "3.8"
services:
  db:
    image: postgres:15
    container_name: aus_pokies_db
    environment:
      POSTGRES_DB: aus_pokies
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: superuser
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init/sql:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"
  
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: aus_pokies_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: stephen@datarecipes.info
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  db-data: